### PR TITLE
Resolve CDN issues, by removing CDN

### PR DESCRIPTION
**Pull request by BenjaminMichaelis**
Fixes IntelliTect/EssentialCSharpManuscript#798

### CODE REVIEW

**Comment by twofingerrightclick** [comment]
We might want to just use npm instead of manually keeping track of these packages. And we could use this extension[extension](https://github.com/OdeToCode/UseNodeModules/tree/master/src/OdeToCode.UseNodeModules)  to handle requests for them. There is probably a better way though.

**Comment by BenjaminMichaelis** [comment]
Disadvantages of npm: every developer needs to install the npm packages, and also we have to deal with copying the files from node_modules into wwwroot.

Andrew seemed to suggest that self served is better than using a CDN as a CDN doesn't benefit from caching advantages anymore.

**Comment by BenjaminMichaelis** [comment]
I can reduce the files to just the necessary ones

**Comment by twofingerrightclick** [comment]
> I can reduce the files to just the necessary ones

You're right... NPM would also potentially require bundling modules and dependencies versus the CDN files that you downloaded already having that done.

**Pull request merged**
